[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
mypy_path = "stubs"

[tool.ruff]
target-version = "py311"
exclude = ["stubs"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D100", "D101", "D103", "D104", "D203", "D212", "COM812", "ISC001"]

[tool.djlint]
profile = "jinja"
ignore="H030,H031"